# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-22 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_auto_20161104_0119'),
        ('fileupload', '0002_auto_20170116_1307'),
        ('users', '0004_auto_20160412_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmd', models.TextField(null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.Category')),
                ('fileupload', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fileupload.FileUpload')),
                ('userprofile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile')),
            ],
        ),
    ]
