# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-12 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0002_auto_20170116_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='pathname',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
