# Generated by Django 2.0.2 on 2018-02-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0003_fileupload_pathname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(upload_to='upload'),
        ),
    ]
