# Generated by Django 2.0.2 on 2018-02-26 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0004_auto_20180223_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='pathname',
        ),
    ]
