# Generated by Django 2.0.2 on 2018-02-23 10:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_auto_20170116_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='fiscal_id',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(code='invalid_ID_fiscal', message="Fiscal ID must be entered in the format: 'YYYYNNNN' where YYYY is the year and NNNN the id. Only 8 digits allowed.", regex='^[0-9]{8}$')], verbose_name='Fiscal ID'),
        ),
        migrations.AlterField(
            model_name='page',
            name='filename',
            field=models.CharField(default='blank', max_length=255, verbose_name='filename'),
        ),
    ]
