# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-04 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_category_random'),
    ]

    operations = [
        migrations.AddField(
            model_name='typecategory',
            name='default',
            field=models.BooleanField(default=True, verbose_name='default'),
        ),
        migrations.AlterField(
            model_name='category',
            name='random',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
