# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-15 09:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0004_templatetrimester'),
        ('companies', '0004_company_random'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='trimester_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utils.TemplateTrimester'),
        ),
    ]
