# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-23 23:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_auto_20161104_0119'),
        ('companies', '0005_company_trimester_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelTrimester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Name of the model trimester')),
                ('categories', models.ManyToManyField(blank=True, to='categories.TypeCategory', verbose_name='Types of category')),
            ],
        ),
        migrations.RemoveField(
            model_name='company',
            name='trimester_template',
        ),
        migrations.AddField(
            model_name='company',
            name='model_trimester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.ModelTrimester'),
        ),
    ]
