# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-19 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0005_auto_20171225_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscalyear',
            name='priority',
            field=models.IntegerField(null=True, verbose_name='Priority'),
        ),
    ]
