# Generated by Django 2.0.2 on 2018-02-23 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0006_fiscalyear_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatetrimester',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.FiscalYear'),
        ),
    ]
